### ISSUE TITLE
知乎百度useragent修改

### ISSUE THREAD

**Issue by hydra77** [zZPiglet/Task#12]
QuanX的那个百度和知乎的useragent修改，在surge要怎么修改呢？

**Comment by zZPiglet** [comment]
> QuanX的那个百度和知乎的useragent修改，在surge要怎么修改呢？

我没有 Surge，可以尝试把相关脚本链接发给会使用 Surge 的用户，或者 Telegram 中 Surge 的讨论群组里问问。如果知道怎么改了可以来这教我一下，非常感谢！

**Comment by zZPiglet** [comment]
https://raw.githubusercontent.com/zZPiglet/Task/master/ChangeUA.sgmodule
