### ISSUE TITLE
⭕️X v1.0.13-build355自动获取不了ck，手动填入ck后，运行脚本显示错误

### ISSUE THREAD

**Issue by xiazhijueju** [zZPiglet/Task#14]
同样是手动获取的微博ck，填入到boxjs。loon的微博通知可以正常运行，而⭕️X却显示获取ck失败。
loon是最新TF版本203，⭕️X是最新商店测试版本355
通知显示如下：
微博通知- Cookie错误
❌Cookie失效

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by zZPiglet** [comment]
@xiazhijueju 暂未能复现，请提供 BoxJs 截图，以及开启测试环境之后的运行日志。
