### ISSUE TITLE
loonTF微博通知不行跳转到Safari

### ISSUE THREAD

**Issue by xiazhijueju** [zZPiglet/Task#15]
请问微博通知的链接是不是不支持在loon跳转？每次点击链接都只会跳到loon软件。⭕️X试过能够正常跳转到Safari。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by zZPiglet** [comment]
@xiazhijueju 疑似软件 bug，主界面手动执行可以跳转，NE 环境自动执行无法跳转。
