### ISSUE TITLE
请问可以支持一下 surge module 吗？

### ISSUE THREAD

**Issue by Six9od** [zZPiglet/Task#17]
不知道如何把 QX 的 “ChangeUA” 这个改成 Surge，请问可以支持一下吗？谢谢

**Comment by zZPiglet** [comment]
@Six9od 具体哪个需要支持呢

**Comment by Six9od** [comment]
Change UA 这个，感谢！> @Six9od 具体哪个需要支持呢

**Comment by zZPiglet** [comment]
https://raw.githubusercontent.com/zZPiglet/Task/master/ChangeUA.sgmodule
