### ISSUE TITLE
大佬你好关于token

### ISSUE THREAD

**Issue by xiaobaizhongdexiaobai** [zZPiglet/Task#2]
大佬你好，小白问下微信小程序 活动抽奖 配置完全按着你写的做 但是按签到没反应。我的是QX商店版

**Comment by zZPiglet** [comment]
方便的话可以发一下自己的配置截图吗？
建议再核对一下 rewrite 及 hostname，以及商店版只能使用本地脚本，请确认脚本路径正确。

**Comment by xiaobaizhongdexiaobai** [comment]
大佬你好，谢谢你的回复。
这个是我的配置![image](https://user-images.githubusercontent.com/38172018/78500819-45987400-778b-11ea-8fcc-eeb9b83f6fc5.png)![image](https://user-images.githubusercontent.com/38172018/78500824-4cbf8200-778b-11ea-911f-385485ed7b49.png)![Uploading 78500829...]()
都是按照你写的做，京东 爱奇艺 网易云音乐都可以用，就是微信这个活动抽奖的不行 试好多次了

**Comment by zZPiglet** [comment]
请核对脚本路径，在你的配置中 WeChatLottery_new.js 路径不一致。关于脚本路径可以在[这个教程](https://www.notion.so/kopshawn/Quantumult-X-1d32ddc6e61c4892ad2ec5ea47f00917)中进行了解。

**Comment by xiaobaizhongdexiaobai** [comment]
大佬你好，活动抽奖小程序搞了几天了，还是不行，所有的脚本都可以用，就他不行 点了签到没有提示 没反应，真的找不到原因啊![image](https://user-images.githubusercontent.com/38172018/78682884-2b909a00-7921-11ea-8482-7cdb747d8e89.png)

**Comment by zZPiglet** [comment]
请核对把脚本存在哪儿了，cron 及 rewrite 后接的脚本路径是否正确。由你之前发的图可以看出你填写了两个路径： (iCloud Drive/Quantumult X/Scripts/)nzw9314/Task/WeChatLottery_new.js 及 (iCloud Drive/Quantumult X/Scripts/)WeChatLottery_new.js
请修改为正确的路径。
如果你在 [NobyDa Script](https://t.me/joinchat/JikZ61Y-WyLUu6dBFPfu6w) 群组中，可参考[此段聊天记录附近](https://t.me/c/1446927138/350701)。

**Comment by xiaobaizhongdexiaobai** [comment]
终于搞好了，V1 V2都要填上才能获取 谢谢大佬你发的群，帮助很大！谢谢🙏
