### ISSUE TITLE
百度UA打开百度系列产品网页显示空白

### ISSUE THREAD

**Issue by MisterGlasses** [zZPiglet/Task#20]
百度那边不知道做了什么手脚，现在访问相关搜索 知道 贴吧之类的百度产品，有一定概率会空白页。
经测试，发现点击如下图所示的超链接时会空白。
![9A856DA4-909D-4574-95A3-4E3B793BAD52](https://user-images.githubusercontent.com/27768847/97199918-89b49a00-17eb-11eb-9195-fb37edc2f2f6.jpeg)
![5D2C4B45-76FF-42C1-A65B-FB89D4C5A598](https://user-images.githubusercontent.com/27768847/97200343-0c3d5980-17ec-11eb-822a-fc7e2053153b.png)
网址为以下样式，在经过两到三次urldecode解码后能看到跳转链接。
`https://boxer.baidu.com/scheme?scheme=baiduboxapp%3A%2F%2Fv1%2Fbrowser%2Fopen%3Furl%3Dsearch%253A%252F%252Furldecode%253Frqid%253D8378498527830491416%26newwindow%3D0%26upgrade%3D1%26append%3D1%26fromwise%3D1%26simple%3D1%26next%3Dbaiduboxapp%253A%252F%252Fv1%252Fbrowser%252Fopen%253Furl%253Dhttps%25253A%25252F%25252Fm.baidu.com%25252Ffrom%25253D1000539d%25252Fssid%25253D0%25252Fuid%25253D0%25252Fbd_page_type%25253D1%25252Fpu%25253Dusm%252525403%2525252Csz%252525401320_2001%2525252Cta%25252540iphone_1_14.0_22_3.6%25252Fbaiduid%25253D9D9BAA9C2216C0CCA35C014C55926AF3%25252Fw%25253D0_10_%25252Ft%25253Diphone%25252Fl%25253D1%25252Ftc%25253Fclk_type%25253D1%252526vit%25253Dosres%252526l%25253D1%252526baiduid%25253D9D9BAA9C2216C0CCA35C014C55926AF3%252526t%25253Diphone%252526ref%25253Dwww_iphone%252526from%25253D1000539d%252526ssid%25253D0%252526lid%25253D8378498527830491416%252526bd_page_type%25253D1%252526pu%25253Dusm%252525403%2525252Csz%252525401320_2001%2525252Cta%25252540iphone_1_14.0_22_3.6%252526order%25253D2%252526fm%25253Dalop%252526isAtom%25253D1%252526is_baidu%25253D0%252526dict%25253D-1%252526tj%25253Dbk_polysemy_2_0_10_lNaN%252526clk_info%25253D%2525257B%25252522tplname%25252522%2525253A%25252522bk_polysemy%25252522%2525252C%25252522srcid%25252522%2525253A1547%2525252C%25252522t%25252522%2525253A1603725635349%2525252C%25252522xpath%25252522%2525253A%25252522div-article(normal)-header-div-div-h3-span%25252522%2525257D%252526wd%25253D%252526eqid%25253D7446680516784118100000005f96e72f%252526w_qd%25253DIlPT2AEptyoA_yikDkudHiA8uw3%252526bdver%25253D2%252526tcplug%25253D1%252526sec%25253D7479%252526di%25253D358e027992394ec8%252526bdenc%25253D1%252526nsrc%25253DFydYV5L2%2525252FeGw6EM0C%2525252BbozP%2525252BEFpMajWLBTNRq2ogTUyTRXumSUBq8Hf6NVeqEgxwA9lgUG0Zbola95p3WBkofHShjcTNpZCYQ%2525252FGxdAeq11IM%2525253D%252526rfrom%25253D1022817p%252526rqid%25253D8378498527830491416%2526newwindow%253D0%2526simple%253D1%2526fromwise%253D1%26needlog%3D1%26logargs%3D%257B%2522source%2522%253A%25221022817p%2522%252C%2522from%2522%253A%2522openbox%2522%252C%2522page%2522%253A%2522safari%2522%252C%2522type%2522%253A%2522%2522%252C%2522value%2522%253A%2522%2522%252C%2522channel%2522%253A%2522%2522%252C%2522extlog%2522%253A%257B%2522ext_content%2522%253A%257B%2522from%2522%253A%25221000539d%2522%252C%2522browserid%2522%253A%252222%2522%252C%2522qid%2522%253A%25228378498527830491416%2522%252C%2522sids%2522%253A%2522154770_146000_147934_156258_158405_152056_156817_156286_150775_154258_148867_156098_154606_156637_153715_158927_154173_150772_151017_157913_156515_127969_154413_154174_155962_159064_152982_158528_154014_155319_146732_158745_152879_131423_157704_154037_153149_148425_157017_107311_158055_158096_154189_155344_155255_157171_157790_144966_154644_154212_157814_139883_158640_157965_147552_158368_158505_158127_153857_158415_157697_154639_159156_159093_154357_158686_159074_110085_157006%2522%252C%2522timestamp%2522%253A1603725635421%252C%2522isPrivate%2522%253Afalse%252C%2522invokeId%2522%253A%25228378498527830491416_1603725635417%2522%257D%257D%252C%2522baiduId%2522%253A%25229D9BAA9C2216C0CCA35C014C55926AF3%253AFG%253D1%2522%252C%2522app_now%2522%253A%2522safari_1603725635423_4387366515%2522%257D&source=1022817p&channel=&target=https%3A%2F%2Fm.baidu.com%2Ffrom%3D1000539d%2Fssid%3D0%2Fuid%3D0%2Fbd_page_type%3D1%2Fpu%3Dusm%25403%252Csz%25401320_2001%252Cta%2540iphone_1_14.0_22_3.6%2Fbaiduid%3D9D9BAA9C2216C0CCA35C014C55926AF3%2Fw%3D0_10_%2Ft%3Diphone%2Fl%3D1%2Ftc%3Fclk_type%3D1%26vit%3Dosres%26l%3D1%26baiduid%3D9D9BAA9C2216C0CCA35C014C55926AF3%26t%3Diphone%26ref%3Dwww_iphone%26from%3D1000539d%26ssid%3D0%26lid%3D8378498527830491416%26bd_page_type%3D1%26pu%3Dusm%25403%252Csz%25401320_2001%252Cta%2540iphone_1_14.0_22_3.6%26order%3D2%26fm%3Dalop%26isAtom%3D1%26is_baidu%3D0%26dict%3D-1%26tj%3Dbk_polysemy_2_0_10_lNaN%26clk_info%3D%257B%2522tplname%2522%253A%2522bk_polysemy%2522%252C%2522srcid%2522%253A1547%252C%2522t%2522%253A1603725635349%252C%2522xpath%2522%253A%2522div-article(normal)-header-div-div-h3-span%2522%257D%26wd%3D%26eqid%3D744668051678 `

**Comment by zZPiglet** [comment]
这个 scheme 应该是跳转 app 用的，跳转失败就空白了。应该不是由 ChangeUA 引起的，且使用 ChangeUA 基本上就是为了不用 app，所以不能跳转也算是目的之一。

**Comment by MisterGlasses** [comment]
我不用ua再测试测试吧
