### ISSUE TITLE
微博跳转到vvebo打开

### ISSUE THREAD

**Issue by MisterGlasses** [zZPiglet/Task#21]
刚刚看到`微博通知增加跳转 VVebo 3.1.7(4)+ `这条更新。
能不能通过写一个脚本，在访问`https://m.weibo.cn/detail/4566249247868466`时，自动跳转到`vvebo://status?id=4566249247868466 `？
或者在网页上加一下跳转按钮？

**Comment by zZPiglet** [comment]
因为 vvebo:// 不是标准 url，所以无法通过简单的 30x 重写直接跳转，不过可以实现使用重写脚本，检测到 https://m.weibo.cn/detail/ 之后弹出通知点击跳转，也可以利用重写脚本实现修改网页（当然可以增加跳转按钮，不过是否可以跳转第三方 URL Scheme 需要看浏览器的限制）。不过我不太理解这个需求点是什么，如果我用网页浏览了微博，为什么还需要跳转到 VVebo 呢？

**Comment by MisterGlasses** [comment]
只是网页端在查看评论等操作上有所限制 总体还是不如vvebo中浏览方便

**Comment by zZPiglet** [comment]
这样的话直接在 VVebo 中查看微博不就好了。

**Comment by MisterGlasses** [comment]
`https://fuliba2020.net/2020151.html`
需求太小众了 主要是像上面的网站会推荐一些微博   经过qx通知再跳转的话 感觉太麻烦了

**Comment by zZPiglet** [comment]
如果不想通过 Quantumult X 通知跳转的话，只能采取对返回体进行修改。有两种方案可选：

1. 直接对 https://fuliba2020.net/2020151.html 这类网站进行修改，将其中超链接中的微博链接替换为 VVebo 的 URL Scheme，可以使用[脚本修改 html](https://github.com/crossutility/Quantumult-X/blob/master/sample-rewrite-with-script.js) 或者直接使用[正则型 url response-body ](https://github.com/crossutility/Quantumult-X/blob/master/rewrite.md#modify-http-response-body)修改，需要注意的是，由于微博的链接自身比较乱，所以要判断是 id 还是 mid 再使用 VVebo 提供的 URL Scheme (vvebo://status?mid=, vvebo://status?id=)。
2. 在微博详情页中添加一个跳转按钮/超链接，这种方法只能使用[脚本修改 html](https://github.com/crossutility/Quantumult-X/blob/master/sample-rewrite-with-script.js) 。

可自行参考文档尝试着写一下。

**Comment by MisterGlasses** [comment]
> 如果不想通过 Quantumult X 通知跳转的话，只能采取对返回体进行修改。有两种方案可选：
> 
> 1. 直接对 https://fuliba2020.net/2020151.html 这类网站进行修改，将其中超链接中的微博链接替换为 VVebo 的 URL Scheme，可以使用[脚本修改 html](https://github.com/crossutility/Quantumult-X/blob/master/sample-rewrite-with-script.js) 或者直接使用[正则型 url response-body ](https://github.com/crossutility/Quantumult-X/blob/master/rewrite.md#modify-http-response-body)修改，需要注意的是，由于微博的链接自身比较乱，所以要判断是 id 还是 mid 再使用 VVebo 提供的 URL Scheme (vvebo://status?mid=, vvebo://status?id=)。
> 2. 在微博详情页中添加一个跳转按钮/超链接，这种方法只能使用[脚本修改 html](https://github.com/crossutility/Quantumult-X/blob/master/sample-rewrite-with-script.js) 。
> 
> 可自行参考文档尝试着写一下。

方案1更好些 省了打开微博后跳转这一步了 多谢大佬 不过我可能没有写脚本的能力 先凑活用着吧😂
