### ISSUE TITLE
关于如何在docker上运行滴滴活动脚本

### ISSUE THREAD

**Issue by otis2020** [zZPiglet/Task#32]
请问大佬，想在docker里运行didi_new和这个滴滴喝水的话，请问应该怎么配置滴滴token，请问是不是在didi.json里添加，求一个格式，不知道该怎么添加进去

**Comment by zZPiglet** [comment]
> 请问大佬，想在docker里运行didi_new和这个滴滴喝水的话，请问应该怎么配置滴滴token，请问是不是在didi.json里添加，求一个格式，不知道该怎么添加进去

不是，由于早期脚本沿用问题导致需要另一个 json，五一假期会对 docker 环境变量进行支持。

**Comment by otis2020** [comment]
> > 请问大佬，想在docker里运行didi_new和这个滴滴喝水的话，请问应该怎么配置滴滴token，请问是不是在didi.json里添加，求一个格式，不知道该怎么添加进去
> 
> 不是，由于早期脚本沿用问题导致需要另一个 json，五一假期会对 docker 环境变量进行支持。

感谢

**Comment by otis2020** [comment]
可不可以顺道添加个LOON的订阅，谢谢大佬~

**Comment by l107868382** [comment]
大佬，现在支持docker运行了吗？
