### ISSUE TITLE
【Oclean】能不能求大佬移植Oclean的签到到青龙上

### ISSUE THREAD

**Issue by FlechazoPh** [zZPiglet/Task#40]
原脚本是 https://github.com/zZPiglet/Task/blob/master/Oclean/Oclean.js
在手机上比较麻烦并且耗电，希望能在青龙上运行，配置Cookie就好，Oclean的cookie的时间也挺长的

**Comment by zZPiglet** [comment]
https://raw.githubusercontent.com/winterfell2021/Surge/master/scripts/oclean.js
