### ISSUE TITLE
请问Haidilao/中的Haidilao.js与HaidilaoUsebonus.js有什么区别，应该使用哪个？

### ISSUE THREAD

**Issue by vhvg** [zZPiglet/Task#5]

**Comment by zZPiglet** [comment]
> *No description provided.*

非常感谢您的关注，Haidilao 系列有段时间没有维护了，之后可能会再更新维护一下。Haidilao.js 只支持签到获得奖励。HaidilaoUsebonus.js 支持自动使用奖励，但是未完成，仅能自动对第一个兑换了锅底的锅自动添加柴火，属于测试脚本。建议先使用 Haidilao.js，或使用 @chavyleung 库的 [haidilao](https://github.com/chavyleung/scripts/tree/master/haidilao)。

**Comment by vhvg** [comment]
好的，感谢您的脚本
