### ISSUE TITLE
oclean签到脚本获取不到cookie

### ISSUE THREAD

**Issue by CostinYuan** [zZPiglet/Task#6]
用的oclean的app，进入活动中心没有提示。然后自己手动签到，还是没有反应。
返回qx运行task显示cookie为空

**Comment by zZPiglet** [comment]
@CostinYuan 先写好获取 cookie 的配置，再进去软件，进入活动才行，app 有缓存，之前进入过一次第二次就不会触发了。实在不行可以尝试小程序版，签到是一致的。

**Comment by CostinYuan** [comment]
...忘写hostname了，不好意思
