### ISSUE TITLE
微信小程序-活动抽奖 无法参加抽奖

### ISSUE THREAD

**Issue by Coolrui1816** [zZPiglet/Task#8]
大佬请问一下这个是什么问题，持续好几周了，等于是无用了。。

上个月十几号的时候刚开始用是正常的，参与了三百多个抽奖，现在一直是出现如图提示，或者是运行js后没反应。

![WechatIMG9](https://user-images.githubusercontent.com/56864168/89993440-4c933e00-dcb9-11ea-8b2b-ead446cbd1f1.jpeg)

**Comment by zZPiglet** [comment]
活动抽奖已无实际意义，早已不再维护，建议删除。
